version: "3.9"

services:
  blackout:
    build: ./blackout
    depends_on:
      - redis
      - celery
    environment:
      REDIS_URL: redis://redis:6379
    volumes:
      - ./blackout:/blackout
    # ports:
    #   - 8000:8000
  nginx:
    image: nginx:stable
    depends_on:
      - blackout
    ports:
      - 80:80
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
  redis:
    image: redis:bullseye
  celery:
    build: ./blackout
    command: celery -A blackout worker -l INFO
    depends_on:
      - redis
    volumes:
      - ./blackout:/usr/src/app
    environment:
      CELERY_BROKER: redis://redis:6379
      CELERY_BACKEND: redis://redis:6379
